### ISSUE TITLE
Function-specific examples

### ISSUE THREAD

**Issue by lawinslow** [USGS-R/smwrGraphs#10]
Is there any interest in moving the function specific examples out of the Vignettes and into the help files? It would make a lot of the functions easier to learn if you didn't have to go digging to find the examples. It looks like there are really good examples there, they'd just need to get put in the vignettes. (Also, the vignettes are somewhat harder for a beginner to use if a package isn't on CRAN).

I'd be happy to work on this if there were interest.

**Comment by ldecicco-USGS** [comment]
I too would like to see the examples in the help files. Even as a non-beginner, I spend a fair amount of time trying to figure out which vignette I should open to answer my question. 

Side question though, why does being on/off CRAN matter for the vignettes?

**Comment by lawinslow** [comment]
It's pretty easy to steer people to the CRAN page for each package, where they get a list of HTML links to vignettes. Explaining the `vignettes` command is much harder, especially for beginners (honestly, I don't really like it either, no tab-complete on Vignette topics, so typos are rampant).

**Comment by lawinslow** [comment]
Also, this is something we could partially fix with GRAN if we create package pages.

**Comment by dlorenz-usgs** [comment]
The basic problem with moving the examples out of vignettes and into the
help files is that the functions in smwrGraphs do not stand alone. There
always needs to be the graphics set up. And for anything other than the
high-level graphics function more set up.

I know I learn a lot more from vignettes than I do from the examples,
especially for more complicated systems.

**Comment by ldecicco-USGS** [comment]
But there's nothing preventing a bunch of ideas to be put together in one example. For example, the `addGrid` function, the example could still be:

```r
set.seed(3636)
X <- rnorm(32)
Y <- X + rnorm(32)

setGD()
# Step 1
AA.pl <- xyPlot(X, Y, Plot=list(what="none"))
# Step 2
addGrid(AA.pl)
AA.pl <- addXY(X, Y, Plot=list(what="points"))
graphics.off()
```

It can be wrapped in a \dontrun{} if the graphic device is failing the examples checks.

**Comment by lawinslow** [comment]
Yeah, I think it would be a really big help for beginners and experienced users alike. I often want the examples to just refer to. Access to the example is much quicker than with a Vignette.

**Comment by dlorenz-usgs** [comment]
I suppose, but graphics.off() would destroy the graphics device, so would
need to be removed.

But my point in the vignette is that you need to set up the graph, add the
grid and then plot the data. that is not clear from the example.

**Comment by lawinslow** [comment]
What prevents you from just putting that all in the example? There are plenty of long examples that include multiple functions from a package.

**Comment by ldecicco-USGS** [comment]
To me, that example *did* clear up that I need to set up the graph, add the grid, and then plot the data.

**Comment by dlorenz-usgs** [comment]
This is a losing fight for me as Laura will review the package and I'll
will need to add examples. I'll just add examples. I have no time in the
next 3 weeks to do that though.

**Comment by ldecicco-USGS** [comment]
Ahh...but @lawinslow  just volunteered to do it!

**Comment by lawinslow** [comment]
I'll try to get around to a preliminary round and make a pull-request.

**Comment by dlorenz-usgs** [comment]
Sounds fine. I apologize for being a  bit short in my response. You have to
realize that 90% of the people that I interact with do not start with a
programing background, so the help file and the examples are not their
primary source of learning about a function. They really appreciate the
vignettes and i get good positive feedback on them. But I do realize that
more experienced coders rely more heavily on the help files. I'm happy that
Luke can work on them.

I had made a couple of changes to boxPlot.R and timePlot.R, just some
little tweaks to the documentation. I pushed my changes so that Master is
current now. I'll avoid working in smwrGraphs until I get more feedback
from Luke.

**Comment by lawinslow** [comment]
Continue moving forward on what you're doing. My goal is simply to take some of the examples in the vignettes and duplicate them in the function documentation. It won't matter to me if you're working on the code at the same time.

**Comment by dlorenz-usgs** [comment]
I do not have anything planned for that code. The next step is review for
publication.

**Comment by dlorenz-usgs** [comment]
Examples are in the help files.
