### ISSUE TITLE
Add ability to place plot labels inside of plot margin

### ISSUE THREAD

**Issue by tmills-usgs** [USGS-R/smwrGraphs#12]
When laying out multiple plots with a shared X axis using 
```R
setLayout(...,shared.x=TRUE) 
```
there is not sufficient space between plot margins for the title to be added. Plot titles (e.g. "A", "B", etc.) need to be able to be placed inside the margin as with 

```R
addExplanation(...,where="ul") 
```

Additionally, many people prefer for labels to be inside the margin regardless of the layout. Currently, I have to edit in another software package after I export.

**Comment by dlorenz-usgs** [comment]
The function addTitle now has an additonal; argument called position that
will allow the use to place the title inside the graph. With the
Justification argument, the title can be placed in the upper-left or
upper-right corners or centered in the upper part of the graph.

**Comment by tmills-usgs** [comment]
Excellent! I will give it a test drive
