### ISSUE TITLE
Cheat sheet for plot parameters

### ISSUE THREAD

**Issue by tmills-usgs** [USGS-R/smwrGraphs#13]
A cheat sheet for parameters to pass to plots is sorely needed, especially for the color and symbol types.

```R
Plot=list(color="",symbol="",...)
```
Even for a relatively experienced R graphics user it is not apparent from the documentation what symbols, colors, or other parameters can be passed to plot to change the appearance.

Something similar to the cheat sheets available for ggplot2 would be very helpful. 

For example:
http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/

**Comment by dlorenz-usgs** [comment]
The documentation for setPlot lists all of the options for what, symbol,
width, and type. A cross reference to setPlot is the See Also section would
be a helpful addition to the documentation for any plotting function that
uses the Plot argument.

Cheat sheets would be great but would require additional support.

**Comment by tmills-usgs** [comment]
A cross reference as you suggested would probably be sufficient. 

Also, a list of color values would be helpful.

**Comment by dlorenz-usgs** [comment]
Specific colors can be obtained from colors().

I can add a section to the Graph Additions showing colors from the color
ramp functions in smwrGraphs. At this point, that kind of addition must be
requested by reviewers, otherwise, it is hard to explain any changes to the
package.

**Comment by dlorenz-usgs** [comment]
Added demo script to display the color ramps.
