### ISSUE TITLE
setPage() appears to be passing unnecessary arguments to device()

### ISSUE THREAD

**Issue by tmills-usgs** [USGS-R/smwrGraphs#14]
When using setPage to output plot as a format other than pdf the function fails with the following error:

```R
setPage(layout = "portrait", font = "preview", name = "USGS",
        multiple = FALSE, device = "svg")
```

```
Error in device(width = width, height = height, pointsize = fontSize,  : 
  unused arguments (rescale = "fixed", title = name, record = multiple)
```

**Comment by tmills-usgs** [comment]
Also similar error for defaults settings:

```R
setPage()
```

```
Error in device(width = width, height = height, pointsize = fontSize,  : 
  unused arguments (width = width, height = height, pointsize = fontSize, rescale = "fixed", title = name, record = multiple)
```

**Comment by tmills-usgs** [comment]
setPage() appears to be passing unnecessary arguments to device()

**Comment by dlorenz-usgs** [comment]
The function setPage does not set up arbitrary graphics devices. It is
intended only to set up onscreen devices: windows, quartz, and X11. Each
output device requires its own peculiar arguments to set up correctly to
handle the requirements of the smwrGraphics environment. As of the current
version, only the onscreen devices and pdf (required for publication
graphs, using setPDF, and vignettes, using setSweave) and png (used in
markdown, using setPNG).

**Comment by tmills-usgs** [comment]
I was using an outdated version of te package. setPNG and additional set.. functions provided the functionality I was looking for.
Thanks!
