### ISSUE TITLE
Locks up RStudio

### ISSUE THREAD

**Issue by bbreaker** [USGS-R/smwrGraphs#15]
For some reason, when I launch smwrGraphs... RStudio hangs up. When I launch any other package that uses smwrGraphs... RStudio hangs up trying to launch swmrGraphs (at "Loading required package: smwrGraphs").  I've tried every version of R from 3.1.1 to 3.2.1. I've uninstalled and reinstalled R and RStudio. Any help here is greatly appreciated.

**Comment by ldecicco-USGS** [comment]
Could you past the results of `sessionInfo()` here?

**Comment by bbreaker** [comment]
R version 3.2.1 (2015-06-18)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.1

**Comment by ldecicco-USGS** [comment]
-  I would add 'GRAN' as a R repository to your Rprofile like this (this gets you updates automatically to USGS packages):
```r
source("http://owi.usgs.gov/R/add_gran_repo.R")
```

-  Restart RStudio.

-  Then, try installing `smwrGraphs` again:
```r
install.packages("smwrGraphs")
```

If you don't want to change your Rprofile, simply:
```r
install.packages("smwrGraphs", 
    repos=c("http://owi.usgs.gov/R",
    "http://cran.us.r-project.org"))
```

-  Restart again

-  If you are still having issues (install the `devtools` package if you don't have it) and paste the results of:
```r
devtools::session_info()
```
(there's more useful information there)

(I spent more time trying to make a numbered list here than actually writing out the comment...bullets will have to do)

**Comment by bbreaker** [comment]
Session info -------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.1 (2015-06-18)
 system   i386, mingw32               
 ui       RStudio (0.99.448)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Chicago             

Packages -----------------------------------------------------------------------------------------------------------------------------
 package   * version date       source        
 curl        0.9     2015-06-19 CRAN (R 3.2.1)
 devtools  * 1.8.0   2015-05-09 CRAN (R 3.2.1)
 digest      0.6.8   2014-12-31 CRAN (R 3.2.1)
 git2r       0.10.1  2015-05-07 CRAN (R 3.2.1)
 memoise     0.2.1   2014-04-22 CRAN (R 3.2.1)
 Rcpp        0.11.6  2015-05-01 CRAN (R 3.2.1)
 rversions   1.0.1   2015-06-06 CRAN (R 3.2.1)
 xml2        0.1.1   2015-06-02 CRAN (R 3.2.1)

**Comment by ldecicco-USGS** [comment]
Hmm...I switched over to 32-bit to see if I could reproduce, and everything looked OK. My devtools::session_info() is:

```r
Session info -----------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.1 (2015-06-18)
 system   i386, mingw32               
 ui       RStudio (0.99.467)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Chicago             

Packages ---------------------------------------------------------------------------
 package    * version date       source        
 akima        0.5-11  2013-09-16 CRAN (R 3.2.0)
 curl         0.9.1   2015-07-04 CRAN (R 3.2.1)
 devtools     1.8.0   2015-05-09 CRAN (R 3.2.1)
 digest       0.6.8   2014-12-31 CRAN (R 3.1.2)
 git2r        0.10.1  2015-05-07 CRAN (R 3.2.0)
 KernSmooth   2.23-14 2015-02-11 CRAN (R 3.2.1)
 lubridate  * 1.3.3   2013-12-31 CRAN (R 3.1.1)
 magrittr     1.5     2014-11-22 CRAN (R 3.1.2)
 memoise      0.2.1   2014-04-22 CRAN (R 3.1.1)
 plyr         1.8.3   2015-06-12 CRAN (R 3.2.0)
 Rcpp         0.12.0  2015-07-25 CRAN (R 3.2.1)
 rstudioapi   0.3.1   2015-04-07 CRAN (R 3.2.0)
 rversions    1.0.2   2015-07-13 CRAN (R 3.2.1)
 smwrBase   * 1.0.4   2015-05-27 local         
 smwrGraphs * 1.0.11  2015-07-20 local         
 stringi      0.5-5   2015-06-29 CRAN (R 3.2.1)
 stringr      1.0.0   2015-04-30 CRAN (R 3.2.0)
 xml2         0.1.1   2015-06-02 CRAN (R 3.2.0)
```

So, pretty much the same. @dlorenz-usgs , any ideas?

**Comment by bbreaker** [comment]
Though I still never figured out the exact source of the problem, smwrGraphs always opened in R but not RStudio. I tried one more uninstall and install of RStudio. That fixed the problem, whatever it was. Probably a setting I changed in RStudio and forgot about.

Thanks.
