### ISSUE TITLE
Bold Explanation question

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/smwrGraphs#22]
Using `setPNG`, you can see the bold in the boxplot explanations. Using `setPDF`, it is not bolded. Personally, I think that looks better without the bold... but the code seems to indicate it should be bold.

I'm still do not understanding fonts on various devices very well. Do we need to export the bold type fonts to get them in the pdf? Like with qfont (but for wfont)

```r
# Load the smwrGraphs package
library(smwrGraphs)
# Generate a random sample for the box plot
set.seed(27036)
BP <- rchisq(32, 3)
# Generate a small random sample
bp <- rchisq(4, 3)
# Create grouping variables
Gchar <- rep(c("A", "B"), 16)
Gnum <- rep(c(1998, 2002), 16)
```

```r
setPNG()
# Set layout for 1 graph and an explanation
AA.lo <- setLayout(width=1.5, height=4, explanation=list(right=1.5))
# Only need to create the margins once in this case
AA.gr <- setGraph(1, AA.lo)
AA.bp <- boxPlot(BP, margin=AA.gr)
setGraph("explanation", AA.lo)
addExplanation(AA.bp, title=expression(bold("Truncated Boxplot")))
graphics.off()
```

vs.

```r
setPDF()
# Set layout for 1 graph and an explanation
AA.lo <- setLayout(width=1.5, height=4, explanation=list(right=1.5))
# Only need to create the margins once in this case
AA.gr <- setGraph(1, AA.lo)
AA.bp <- boxPlot(BP, margin=AA.gr)
setGraph("explanation", AA.lo)
addExplanation(AA.bp, title=expression(bold("Truncated Boxplot")))
graphics.off()
```

**Comment by dlorenz-usgs** [comment]
This was a good question as it forced me to go back to the original work in selecting substitute fonts for Univers 57 condensed and Univers 67 condensed bold, which are required by the USGS standards. As it happens, the physical size of the 2 Univers fonts are nearly the same, which is very close in physical size to Helvetica-narrow. The quirky thing about Helvetica-narrow is that the bold face is not visually different from the regular face. But the pdf file that is created is tagged with bold or not tagged as the case may be. Other fonts have wider bold face than regular face and do not replicate the appearance of the finished USGS figure. But the contents would be the same.
