### ISSUE TITLE
No ticks on character axis

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/smwrGraphs#25]
I *think* ticks would still be appropriate in this situation:
```
x <- c("A", "B", "C")
y <- 1:3
setPDF()
xyPlot(x,y,Plot=list(what="overlaid"))
graphics.off()
```
And there aren't any now.
![test](https://cloud.githubusercontent.com/assets/1105215/10674291/d096d990-78bf-11e5-94fa-ae872d5faeeb.png)

**Comment by ldecicco-USGS** [comment]
The root cause of this question was because of a column "Period" returned from `rloadest` that has "WY 2006", "WY 2007" etc.

**Comment by dlorenz-usgs** [comment]
The USGS standards guide indicates that ticks are not used for axis with
discrete scales.

It also states "Continuous data plotted on a discrete scale  [is] not
meaningful,do not use." That means discrete values should not show
connecting lines as they stand alone

The example suggests that there is a distinct relation between A and B and
between B and C. There are times when that would be true, for example
sequential years or months, which is the example shown on page 18 of the
standards guide (any kind of ordered factor would also work). But the
standards still suggest no lines.

Note that addAxisLabels will add the ticks in this case--just set ticks to
TRUE and labels to FALSE.

**Comment by ldecicco-USGS** [comment]
Makes sense to me.

**Comment by ldecicco-USGS** [comment]
I forwarded this on to the user who brought up the issue. They only noticed because a reviewer  wanted them to include the ticks. This is good information for responding to that reviewer.
