### ISSUE TITLE
update install instructions in readme.md

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/smwrGraphs#3]
```R
install.packages(c("smwrGraphs"), 
repos=c("http://usgs-r.github.com","http://cran.us.r-project.org"), 
dependencies=TRUE)
```
results in
```
package ‘smwrGraphs’ is available as a source package but not as a binary

Warning message:
package ‘smwrGraphs’ is not available (for R version 3.1.2) 
```

should be 
```R
install.packages(c("smwrGraphs"), 
   repos=c("http://usgs-r.github.com","http://cran.us.r-project.org"), 
   dependencies=TRUE, type = 'both')
```
and also note that for me after changing to `type = 'both'`:
```
Warning message:
In install.packages(c("smwrGraphs"), repos = c("http://usgs-r.github.com",  :
  installation of package ‘RODBC’ had non-zero exit status
```

**Comment by dlorenz-usgs** [comment]
Jordan,
  Are you running on the Mac? The Windows binary should be available. Maybe
it should be conditional on the OS:

install.packages(c("smwrGraphs"),
repos=c("http://usgs-r.github.com","http://cran.us.r-project.org"),
dependencies=TRUE)

for Windows users and

install.packages(c("smwrGraphs"),
   repos=c("http://usgs-r.github.com","http://cran.us.r-project.org"),
   dependencies=TRUE, type = 'both')

for everyone else.

Dave

**Comment by jread-usgs** [comment]
resolved. Thanks @dlorenz-usgs
