### ISSUE TITLE
how to set different symbols

### ISSUE THREAD

**Issue by ching12** [USGS-R/smwrGraphs#38]
I don't know how to use different symbols? Right now all the points have the same symbol, i.e. filled circles, but with different colors. I'm wondering if it would be possible to use different symbols besides colors? Thanks.

**Comment by JonoWatson** [comment]
The solution I found was to create a column in the dataframe where I designated which symbol I wanted displayed, for each value of a particular factor. The setMultiPlot helpfile describes the format of the symbol argument used in the piperPlot function. For example, if there were three lines of data that I wanted presented with different symbols, I would create a column that resembled:

>PD$Symbol <- c("circle","square","downtri")

The piperPlot function (as presented in the piperPlot vignette) would then be: 

> AA.pl <- with(PD, piperPlot(Ca.meq, Mg.meq, Na.meq,
+ Cl.meq, HCO3.meq, SO4.meq,
+ Plot=list(name=SS, symbol=Symbol,
+ zCat.title = "Sodium",
+ xAn.title = "Chloride",
+ yAn.title = "Bicarbonate"))
