### ISSUE TITLE
smwrGraphs

### ISSUE THREAD

**Issue by bertstolp** [USGS-R/smwrGraphs#42]
Trying to install smwrGraphs using the command
 install.packages("smwrGraphs")               and get the following response:

Installing package into ‘C:/Users/bjstolp/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘smwrGraphs’ is not available (for R version 3.3.2)

I have a folder
C:\Users\bjstolp\Documents\R\win-library\3.3     it is empty
I do not have a folder
C:\Users\bjstolp\Documents\R\lib

Thank you

**Comment by ldecicco-USGS** [comment]
Did you follow the "Package Installation" in the "readme" here?
https://github.com/USGS-R/smwrGraphs

It's a bit different than CRAN packages, you need to add a new repository "GRAN".
