### ISSUE TITLE
update

### ISSUE THREAD

**Issue by suisch** [USGS-R/smwrGraphs#43]
Dear colleagues and maintainers of the smwrGraphs,

unfortunately, the current version of smwrGraphs does not seem to work with the current version of R, 3.5.1. 
After doing the recommended 
 rprofile_path = file.path(Sys.getenv("HOME"), ".Rprofile")
 write('\noptions(repos=c(getOption(\'repos\'),
  CRAN=\'https://cloud.r-project.org\',
  USGS=\'https://owi.usgs.gov/R\'))\n',
      rprofile_path,
      append =  TRUE)

the install command
install.packages("smwrGraphs")

issues the message

Installing package into ‘C:/Users/Schmidt/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘smwrGraphs’ is not available (for R version 3.5.1)

It is actually more than a warning, the following call 

 library(smwrGraphs) 

issues the error:
Error in library(smwrGraphs) : there is no package called ‘smwrGraphs’

Last week on another computer which I cannot update to R3.5.1 (for reasons not relevant here), the package worked fine for me.

Also , trying to run the example on the web page 
https://rdrr.io/github/USGS-R/smwrGraphs/man/stiffPlot.html
issues an error:
Error in library(USGS - R/smwrGraphs) : 'package' must be of length 1
Execution halted

I realize that R has undergone a lot of changes recently and that updating packages will probably mean quite some work. Is it planned? When will a new version of smwrGraphs be available?

Best regards and thank you for the nice package,
Susanne

**Comment by ldecicco-USGS** [comment]
My first question would be did you restart R after the `rprofile_path` commands? R will only be aware of the GRAN repo once you restart. So, restart, and let me know if it's still not installing.

**Comment by suisch** [comment]
sorry, I didn't. My mistake. Completely disregarding half the text .. I seem to remember that on the other computer it worked without restarting .. All seems fine now. Thanks for coming back to me so quickly! Note to self: RTFM plus messages .. If you agree we can not only close but hide this issue - except maybe for the web page link that isn't working? which fooled me further into believing that it was a question of package update ..

**Comment by ldecicco-USGS** [comment]
No problem...it happens a lot. 👍 
As for that link, that web page seems to be something they are scraping together from Github...I'm not surprised non-CRAN/Bioconductor packages aren't installed. But...I don't think there's much we can do about it.
