### ISSUE TITLE
Piper plot choose colors/color ramp

### ISSUE THREAD

**Issue by BB-files** [USGS-R/smwrGraphs#48]
Hi, 
I have been trying to produce piper plots for my data, using the standard code (and an added loop. It is working fine, but the color automatically chosen through setColor cannot be differentiated on one of my plots. **Is there any way for me to choose distinct colors for each variable name (Sw, Gw-S,...) I have?** 

```
names<- c('Both rounds','Both regions', 'Both rounds&regionsType1', 'Both rounds&regionsType2')
for (i in 1:4){
setSweave(names[i], 7, 7)
PD$SS <- PD[,(i+1)]
PD$col <- c("green", "red")
AA.pl <- with(PD, piperPlot(Ca.meq, Mg.meq, Na.meq,
                            Cl.meq, HCO3.meq, SO4.meq,
                            Plot=list(name=SS, color= setColor(PD$SS)),
                            zCat.title = "Sodium",
                            xAn.title = "Chloride",
                            yAn.title = "Bicarbonate"))
addExplanation(AA.pl, where="ul", title= names[i])
graphics.off()
}
```

[Both rounds&regionsType2.pdf](https://github.com/USGS-R/smwrGraphs/files/3500788/Both.rounds.regionsType2.pdf)

**Comment by ldecicco-USGS** [comment]
I think you can set the color like you did with PD$col, but then use that "col" column in the `setColor` call:
```r
AA.pl <- with(PD, piperPlot(Ca.meq, Mg.meq, Na.meq,
                            Cl.meq, HCO3.meq, SO4.meq,
                            Plot=list(name=SS, color= setColor(col)), # HERE
                            zCat.title = "Sodium",
                            xAn.title = "Chloride",
                            yAn.title = "Bicarbonate"))

```

**Comment by BB-files** [comment]
Sorry for the late reply and thanks for the help! (...had a slight incline to bang my head against the wall when I saw my mistake ;-))
