### ISSUE TITLE
error with piperplot

### ISSUE THREAD

**Issue by alisamastusgs** [USGS-R/smwrGraphs#50]
Hi,
I get the following error when I run the piperplot function with the example dataset and code.
I get the plot but the legend doesn't appear. Any help would be appreciated.

library(smwrData)
> library(smwrGraphs)
> data(MiscGW)
> PD<- transform(MiscGW, Ca.meq = conc2meq(Calcium, "calcium"),
+                 Mg.meq = conc2meq(Magnesium, "magnesium"),
+                 Na.meq = conc2meq(Sodium, "sodium"),
+                 Cl.meq = conc2meq(Chloride, "chloride"),
+                 SO4.meq = conc2meq(Sulfate, "sulfate"),
+                 HCO3.meq = conc2meq(Bicarbonate, "bicarb"))
> 
> PD$SS<- row.names(PD)
> setSweave("piperplot01", 7, 7)
> AA.pl<- with(PD, piperPlot(Ca.meq, Mg.meq, Na.meq,
+                              Cl.meq, HCO3.meq, SO4.meq,
+                              Plot=list(name=SS, color=setColor(SS)),
+                              zCat.title = "Sodium",
+                              xAn.title = "Chloride",
+                              yAn.title = "Bicarbonate"))
> setGraph("explanation", AA.pl)
> addExplanation(AA.pl)
Error in legend(x = pos, legend = Etext[Seq], title = title, bty = "n",  : 
  argument 6 matches multiple formal arguments
> graphics.off()

**Comment by ldecicco-USGS** [comment]
I'm not sure if there's a problem with the formatting, but the following worked for me:
```r
library(smwrData)
library(smwrGraphs)
data(MiscGW)

PD <- transform(MiscGW, 
               Ca.meq = conc2meq(Calcium, "calcium"),
               Mg.meq = conc2meq(Magnesium, "magnesium"),
               Na.meq = conc2meq(Sodium, "sodium"),
               Cl.meq = conc2meq(Chloride, "chloride"),
               SO4.meq = conc2meq(Sulfate, "sulfate"),
               HCO3.meq = conc2meq(Bicarbonate, "bicarb"))
PD$SS <- row.names(PD)

setSweave("piperplot01", 7, 7)
AA.pl<- with(PD, piperPlot(Ca.meq, Mg.meq, Na.meq,
                           Cl.meq, HCO3.meq, SO4.meq,
                           Plot=list(name=SS, color=setColor(SS)),
                           zCat.title = "Sodium",
                           xAn.title = "Chloride",
                           yAn.title = "Bicarbonate"))
addExplanation(AA.pl)
graphics.off()

```

It might be because you've got both `setSweave` and `setGraph`. If you are trying to save to a pdf, use the `setSweave` and delete the `setGraph`. If you want 2 separate graphs (one for the plot and one for the legend), add a `graphics.off()` before the `setGraph`

**Comment by alisamastusgs** [comment]
Laura,
I restarted Rstudio and it worked fine. My bad.

Another question, since we started using windows defender rstudio is running noticeably slower for me, a simple 1 line command can take several seconds.
Have you heard of anyone else experiencing this?

Thanks Alisa

________________________________

**Comment by alisamastusgs** [comment]
I found a post about reinstalling dplyr and that seems to have solved my problem!

________________________________
