### ISSUE TITLE
smwrBase not available for R version 4.0.1

### ISSUE THREAD

**Issue by omstoken** [USGS-R/smwrGraphs#52]
I ran into this error today when trying to install the smwr packages from github:

Error: Failed to install 'smwrGraphs' from GitHub:
  (converted from warning) package ‘smwrBase’ is not available (for R version 4.0.1)

Will I have to install an older version of R to run the smwr packages?

**Comment by ldecicco-USGS** [comment]
How are you doing this installation? I ran this:
```r
remotes::install_github("USGS-R/smwrBase")
Downloading GitHub repo USGS-R/smwrBase@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                           
2: CRAN packages only            
3: None                          
4: Rcpp (1.0.4.6 -> 1.0.5) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
3
```
and it worked. I typically choose "3" (none), and update my packages with the "Update All" button in RStudio for CRAN packages. It might complain about not having `smwrData` first. The instructions on the README are:
```r
remotes::install_github("USGS-R/smwrData")
remotes::install_github("USGS-R/smwrBase")
```

**Comment by omstoken** [comment]
I had smwrData installed. It seemed the outdated Rcpp was the issue. I was able to install both smwrBase and smwrGraphs after updating that package and selecting option 3 when prompted to update. Thanks for you help and quick response!
